"""FastAPI service exposing FINDHasherOptimized over HTTP.

Endpoints:
  POST /compare  — task.txt p.31 main contract; takes two image uploads,
                   returns FINd hashes + Hamming distance + extensions.
  GET  /health   — liveness probe (Docker HEALTHCHECK / Kubernetes).
  GET  /version  — build metadata for ops debugging.
  GET  /docs     — interactive Swagger UI (auto-generated by FastAPI).

Design decisions are recorded in private_summative/text.txt sections
D7-D12. Briefly:
  D7  — response extensions beyond brief minimum (consultant value-add).
  D8  — input validation strategy (5 categorical bad inputs → 4xx codes).
  D9  — singleton hasher via FastAPI Depends (avoid 500µs DCT init/req).
  D10 — confidence buckets calibrated from measured ROC operating points.
  D11 — Dockerfile strategy (single-stage slim, non-root, HEALTHCHECK).
  D12 — endpoint list rationale.

Closes acceptance criteria T6 (API spec compliance) + T8 (input validation).
"""

from __future__ import annotations

import io
import os
import sys
from pathlib import Path

from fastapi import Depends, FastAPI, File, HTTPException, UploadFile
from PIL import Image

# Make sibling FINd_optimized.py importable when the API runs from project root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from FINd_optimized import FINDHasherOptimized

from api.schemas import (
    CompareResponse,
    HealthResponse,
    ImageMeta,
    VersionResponse,
)

# Maximum upload size — see D8 in text.txt for the 10 MB calibration.
# Override at runtime via env: docker run -e MAX_UPLOAD_BYTES=20000000 ...
MAX_UPLOAD_BYTES = int(os.environ.get("MAX_UPLOAD_BYTES", 10 * 1024 * 1024))

# Confidence bucket thresholds — see D10. Anchored to ROC operating points
# measured on meme_images (FPR ≈ 0.1% at 50 bits, FPR ≈ 1% at 90 bits).
HIGH_CONFIDENCE_BELOW = 50
MEDIUM_CONFIDENCE_BELOW = 90

# Threshold recommendations surfaced in /compare response so clients can
# choose their own operating point per A1/A2/A5 use cases.
THRESHOLD_RECOMMENDATION = {
    "high_precision": 50,   # FPR ≈ 0.1% — auto-action safe
    "balanced": 90,         # FPR ≈ 1%   — recommend human review (use case A)
    "high_recall": 130,     # FPR ≈ 5%   — high-recall scenarios
}


app = FastAPI(
    title="FINd image hashing API",
    description=(
        "FastAPI wrapper around FINDHasherOptimized. POST /compare for the "
        "main hash-and-compare endpoint; see /docs for the interactive "
        "Swagger UI generated from the Pydantic schemas."
    ),
    version="0.1.0",
)


# ---------------------------------------------------------------------------
# Dependencies (singleton hasher, see D9)
# ---------------------------------------------------------------------------

_hasher_instance: FINDHasherOptimized | None = None


def get_hasher() -> FINDHasherOptimized:
    """Return the process-wide FINDHasherOptimized instance.

    Lazy-init on first request. Reused for all subsequent requests because
    the hasher is stateless (DCT_matrix and luma coefficients are read-only
    after construction), so concurrent requests are safe.

    Tests can override via app.dependency_overrides[get_hasher].
    """
    global _hasher_instance
    if _hasher_instance is None:
        _hasher_instance = FINDHasherOptimized()
    return _hasher_instance


# ---------------------------------------------------------------------------
# Validation helpers (see D8)
# ---------------------------------------------------------------------------

async def validate_image(file: UploadFile, field_name: str) -> tuple[Image.Image, bytes]:
    """Validate an uploaded image. Raises HTTPException with a 4xx code on
    any of the five identified bad-input categories (see D8). Returns the
    decoded PIL.Image and the raw bytes (for size_bytes metadata).
    """
    # Category 2: wrong content-type.
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(
            status_code=400,
            detail=f"{field_name} is not an image (content-type: {file.content_type!r})",
        )

    content = await file.read()

    # Category 3: oversized upload (DoS protection).
    if len(content) > MAX_UPLOAD_BYTES:
        raise HTTPException(
            status_code=413,
            detail=(
                f"{field_name} exceeds {MAX_UPLOAD_BYTES // 1024 // 1024} MB limit "
                f"(got {len(content)} bytes)"
            ),
        )

    # Category 4: corrupted / unsupported image data.
    try:
        img = Image.open(io.BytesIO(content))
        img.load()  # force full decode (PIL is lazy by default)
    except Exception as exc:
        raise HTTPException(
            status_code=400,
            detail=f"{field_name} is corrupted or unsupported format: {exc}",
        ) from exc

    # Category 5: degenerate dimensions (would crash integral image div-by-zero).
    if img.width == 0 or img.height == 0:
        raise HTTPException(
            status_code=400,
            detail=f"{field_name} has invalid dimensions: {img.width}x{img.height}",
        )

    return img, content


def bucket_confidence(distance: int) -> str:
    """Map a Hamming distance to a human-interpretable confidence label.

    Cutoffs derived from measured ROC on meme_images (see D10 in text.txt).
    """
    if distance < HIGH_CONFIDENCE_BELOW:
        return "high"
    if distance < MEDIUM_CONFIDENCE_BELOW:
        return "medium"
    return "low"


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.post("/compare", response_model=CompareResponse)
async def compare(
    image1: UploadFile = File(..., description="First image to hash"),
    image2: UploadFile = File(..., description="Second image to hash"),
    hasher: FINDHasherOptimized = Depends(get_hasher),
) -> CompareResponse:
    """Hash both images with FINd and return their Hamming distance.

    Required fields in the response (`image1_hash`, `image2_hash`,
    `distance`) match task.txt p.38 exactly. Additional fields
    (`confidence`, `image1_meta`, `image2_meta`, `threshold_recommendation`)
    are extensions; clients that only need the contract from the brief can
    ignore them.
    """
    img1, content1 = await validate_image(image1, "image1")
    img2, content2 = await validate_image(image2, "image2")

    h1 = hasher.fromImage(img1)
    h2 = hasher.fromImage(img2)
    distance = h1 - h2

    return CompareResponse(
        image1_hash=str(h1),
        image2_hash=str(h2),
        distance=distance,
        confidence=bucket_confidence(distance),
        image1_meta=ImageMeta(
            width=img1.width,
            height=img1.height,
            size_bytes=len(content1),
        ),
        image2_meta=ImageMeta(
            width=img2.width,
            height=img2.height,
            size_bytes=len(content2),
        ),
        threshold_recommendation=THRESHOLD_RECOMMENDATION,
    )


@app.get("/health", response_model=HealthResponse)
def health(hasher: FINDHasherOptimized = Depends(get_hasher)) -> HealthResponse:
    """Liveness probe for Docker HEALTHCHECK / Kubernetes.

    Returns 200 OK with the loaded hasher class name as a debug aid.
    Implicitly verifies the hasher singleton can be retrieved — a failure
    here surfaces as 500 and triggers Docker auto-restart.
    """
    return HealthResponse(status="ok", hasher=hasher.__class__.__name__)


@app.get("/version", response_model=VersionResponse)
def version() -> VersionResponse:
    """Return build metadata.

    GIT_SHA and BUILD_DATE are injected at Docker build time via
    --build-arg; fall back to "unknown" when run outside a build (e.g.
    local `uvicorn api.main:app`).
    """
    return VersionResponse(
        find_version=app.version,
        git_sha=os.environ.get("GIT_SHA", "unknown"),
        build_date=os.environ.get("BUILD_DATE", "unknown"),
    )
